version: '3'

services:
  buildtools:
    image: ghcr.io/electron/devcontainer:3d8d44d0f15b05bef6149e448f9cc522111847e9

    volumes:
      - ..:/workspaces/gclient/src/electron:cached

      - /var/run/docker.sock:/var/run/docker.sock

    command: /bin/sh -c "while sleep 1000; do :; done"

    user: builduser

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
